### ISSUE TITLE
Clash with Categorical Arrays

### ISSUE THREAD

**Issue by hearnsj** [queryverse/QueryTables.jl#4]
David, I am sure you are enjoying JuliaCon.
I tried to install DataTables on Julia 1.1.1 Windows 10

I am not sure where this clash originates from

v1.1) pkg> add DataTables
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package CategoricalArrays [324d7699]:
 CategoricalArrays [324d7699] log:
 ├─possible versions are: [0.0.1-0.0.6, 0.1.0-0.1.6, 0.2.0-0.2.3, 0.3.0-0.3.11, 0.3.13-0.3.14, 0.4.0, 0.5.0-0.5.4] or uninstalled
 ├─restricted by compatibility requirements with DataTables [933ac57d] to versions: [0.0.6, 0.1.0-0.1.6]
 │ └─DataTables [933ac57d] log:
 │   ├─possible versions are: 0.0.1-0.0.3 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions 0.0.1-0.0.3
 └─restricted by julia compatibility requirements to versions: [0.3.11, 0.3.13-0.3.14, 0.4.0, 0.5.0-0.5.4] or uninstalled — no versions left

**Comment by davidanthoff** [comment]
I think this has nothing to do with QueryTables, which is entirely unrelated to CategoricalArrays. I think the error message shows some problem with respect to DataTables.jl, which is a different package.
